name: Deploy Storybook

on:
    push:
        branches: [main, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: https://github.com
        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Building
              run: yarn build-storybook
            - name: set email git config
              run: |
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  git config --get user.email
                  yarn deploy-storybook
